### ISSUE TITLE
First bench bot milestone

### ISSUE THREAD

**Issue by ggwpez** [paritytech/tide-github#4]
Items needed to finish a first minimal version of the bot:  
- [ ] MR Comment listener
- [ ] optional: Authorization
- [ ] Job queue which holds incoming jobs
- [ ] Git wrapper
  - [ ] Checkout the new branch
  - [ ] Commit and push the updated weight files
- [ ] Cargo wrapper
  - [ ] Compile the benchmarks
  - [ ] Execute the benchmarks
- [ ] Result collection and post processing
- [ ] MR Comment poster to publish the results

**Comment by koenw** [comment]
Hey @ggwpez, like I mentioned in our chat this repository was only meant to be a supporting library for the bot and not the bot itself. I've pushed the bot to its own repository and created a similar milestone issue [here](https://github.com/paritytech/bankbot/issues/1), so I'm closing this issue.

Thanks for showing me:)
